# Generated by Django 5.1.1 on 2024-10-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_memberinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='member_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
